quiet: false
all: false
issue-845-fix: true
packages:
  github.com/mediusfy/modulex:
    config:
      dir: mocks
      outpkg: mocks
      filename: "{{.InterfaceName}}.go"
    interfaces:
      Module:
        config:
          structname: MockModule
      EventBus:
        config:
          structname: MockEventBus
      Registry:
        config:
          structname: MockRegistry
      Startable:
        config:
          structname: MockStartable
      Stoppable:
        config:
          structname: MockStoppable
      ServiceRegistry:
        config:
          structname: MockServiceRegistry
      ServiceRegistrar:
        config:
          structname: MockServiceRegistrar
      ServiceResolver:
        config:
          structname: MockServiceResolver
      EventBusProvider:
        config:
          structname: MockEventBusProvider
      ConfigProvider:
        config:
          structname: MockConfigProvider
      LoggerProvider:
        config:
          structname: MockLoggerProvider
      TaskSpawner:
        config:
          structname: MockTaskSpawner
      HealthCheckRegistrar:
        config:
          structname: MockHealthCheckRegistrar
      HealthCheckProvider:
        config:
          structname: MockHealthCheckProvider
      ReadinessRegistrar:
        config:
          structname: MockReadinessRegistrar
      ReadinessProvider:
        config:
          structname: MockReadinessProvider
