quiet: false
all: false
issue-845-fix: true
packages:
  github.com/mediusfy/modulex:
    config:
      dir: mocks
      outpkg: mocks
      filename: "{{.InterfaceName}}.go"
    interfaces:
      Module:
        config:
          structname: MockModule
      EventBus:
        config:
          structname: MockEventBus
      Registry:
        config:
          structname: MockRegistry
      Startable:
        config:
          structname: MockStartable
      Stoppable:
        config:
          structname: MockStoppable
