// Code generated by hand. DO NOT EDIT.
//
// This file holds compile-time assertions that the generated mocks satisfy the
// modulex interfaces they target. If an interface gains new methods but the
// generated mock is not regenerated, the build will fail here instead of in
// consumer code.

package mocks

import "github.com/mediusfy/modulex"

var (
	_ modulex.ConfigProvider       = (*MockConfigProvider)(nil)
	_ modulex.EventBus             = (*MockEventBus)(nil)
	_ modulex.EventBusProvider     = (*MockEventBusProvider)(nil)
	_ modulex.HealthCheckProvider  = (*MockHealthCheckProvider)(nil)
	_ modulex.HealthCheckRegistrar = (*MockHealthCheckRegistrar)(nil)
	_ modulex.LoggerProvider       = (*MockLoggerProvider)(nil)
	_ modulex.Module               = (*MockModule)(nil)
	_ modulex.ReadinessProvider    = (*MockReadinessProvider)(nil)
	_ modulex.ReadinessRegistrar   = (*MockReadinessRegistrar)(nil)
	_ modulex.Registry             = (*MockRegistry)(nil)
	_ modulex.ServiceRegistrar     = (*MockServiceRegistrar)(nil)
	_ modulex.ServiceRegistry      = (*MockServiceRegistry)(nil)
	_ modulex.ServiceResolver      = (*MockServiceResolver)(nil)
	_ modulex.Startable            = (*MockStartable)(nil)
	_ modulex.Stoppable            = (*MockStoppable)(nil)
	_ modulex.TaskSpawner          = (*MockTaskSpawner)(nil)
)
