// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockConfigProvider is an autogenerated mock type for the ConfigProvider type
type MockConfigProvider struct {
	mock.Mock
}

type MockConfigProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigProvider) EXPECT() *MockConfigProvider_Expecter {
	return &MockConfigProvider_Expecter{mock: &_m.Mock}
}

// GetConfig provides a mock function with given fields: target
func (_m *MockConfigProvider) GetConfig(target interface{}) error {
	ret := _m.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(target)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigProvider_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockConfigProvider_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
//   - target interface{}
func (_e *MockConfigProvider_Expecter) GetConfig(target interface{}) *MockConfigProvider_GetConfig_Call {
	return &MockConfigProvider_GetConfig_Call{Call: _e.mock.On("GetConfig", target)}
}

func (_c *MockConfigProvider_GetConfig_Call) Run(run func(target interface{})) *MockConfigProvider_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockConfigProvider_GetConfig_Call) Return(err error) *MockConfigProvider_GetConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigProvider_GetConfig_Call) RunAndReturn(run func(interface{}) error) *MockConfigProvider_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigProvider creates a new instance of MockConfigProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigProvider {
	mock := &MockConfigProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
