// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	modulex "github.com/mediusfy/modulex"
	mock "github.com/stretchr/testify/mock"
)

// MockEventBusProvider is an autogenerated mock type for the EventBusProvider type
type MockEventBusProvider struct {
	mock.Mock
}

type MockEventBusProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventBusProvider) EXPECT() *MockEventBusProvider_Expecter {
	return &MockEventBusProvider_Expecter{mock: &_m.Mock}
}

// EventBus provides a mock function with no fields
func (_m *MockEventBusProvider) EventBus() modulex.EventBus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventBus")
	}

	var r0 modulex.EventBus
	if rf, ok := ret.Get(0).(func() modulex.EventBus); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(modulex.EventBus)
		}
	}

	return r0
}

// MockEventBusProvider_EventBus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventBus'
type MockEventBusProvider_EventBus_Call struct {
	*mock.Call
}

// EventBus is a helper method to define mock.On call
func (_e *MockEventBusProvider_Expecter) EventBus() *MockEventBusProvider_EventBus_Call {
	return &MockEventBusProvider_EventBus_Call{Call: _e.mock.On("EventBus")}
}

func (_c *MockEventBusProvider_EventBus_Call) Run(run func()) *MockEventBusProvider_EventBus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventBusProvider_EventBus_Call) Return(_a0 modulex.EventBus) *MockEventBusProvider_EventBus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBusProvider_EventBus_Call) RunAndReturn(run func() modulex.EventBus) *MockEventBusProvider_EventBus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventBusProvider creates a new instance of MockEventBusProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventBusProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventBusProvider {
	mock := &MockEventBusProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
