// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHealthCheckRegistrar is an autogenerated mock type for the HealthCheckRegistrar type
type MockHealthCheckRegistrar struct {
	mock.Mock
}

type MockHealthCheckRegistrar_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthCheckRegistrar) EXPECT() *MockHealthCheckRegistrar_Expecter {
	return &MockHealthCheckRegistrar_Expecter{mock: &_m.Mock}
}

// RegisterHealthCheck provides a mock function with given fields: name, check
func (_m *MockHealthCheckRegistrar) RegisterHealthCheck(name string, check func(context.Context) error) error {
	ret := _m.Called(name, check)

	if len(ret) == 0 {
		panic("no return value specified for RegisterHealthCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func(context.Context) error) error); ok {
		r0 = rf(name, check)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHealthCheckRegistrar_RegisterHealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterHealthCheck'
type MockHealthCheckRegistrar_RegisterHealthCheck_Call struct {
	*mock.Call
}

// RegisterHealthCheck is a helper method to define mock.On call
//   - name string
//   - check func(context.Context) error
func (_e *MockHealthCheckRegistrar_Expecter) RegisterHealthCheck(name interface{}, check interface{}) *MockHealthCheckRegistrar_RegisterHealthCheck_Call {
	return &MockHealthCheckRegistrar_RegisterHealthCheck_Call{Call: _e.mock.On("RegisterHealthCheck", name, check)}
}

func (_c *MockHealthCheckRegistrar_RegisterHealthCheck_Call) Run(run func(name string, check func(context.Context) error)) *MockHealthCheckRegistrar_RegisterHealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockHealthCheckRegistrar_RegisterHealthCheck_Call) Return(_a0 error) *MockHealthCheckRegistrar_RegisterHealthCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthCheckRegistrar_RegisterHealthCheck_Call) RunAndReturn(run func(string, func(context.Context) error) error) *MockHealthCheckRegistrar_RegisterHealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthCheckRegistrar creates a new instance of MockHealthCheckRegistrar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthCheckRegistrar(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthCheckRegistrar {
	mock := &MockHealthCheckRegistrar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
