// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHealthCheckProvider is an autogenerated mock type for the HealthCheckProvider type
type MockHealthCheckProvider struct {
	mock.Mock
}

type MockHealthCheckProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthCheckProvider) EXPECT() *MockHealthCheckProvider_Expecter {
	return &MockHealthCheckProvider_Expecter{mock: &_m.Mock}
}

// HealthChecks provides a mock function with no fields
func (_m *MockHealthCheckProvider) HealthChecks() map[string]func(context.Context) error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthChecks")
	}

	var r0 map[string]func(context.Context) error
	if rf, ok := ret.Get(0).(func() map[string]func(context.Context) error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]func(context.Context) error)
		}
	}

	return r0
}

// MockHealthCheckProvider_HealthChecks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthChecks'
type MockHealthCheckProvider_HealthChecks_Call struct {
	*mock.Call
}

// HealthChecks is a helper method to define mock.On call
func (_e *MockHealthCheckProvider_Expecter) HealthChecks() *MockHealthCheckProvider_HealthChecks_Call {
	return &MockHealthCheckProvider_HealthChecks_Call{Call: _e.mock.On("HealthChecks")}
}

func (_c *MockHealthCheckProvider_HealthChecks_Call) Run(run func()) *MockHealthCheckProvider_HealthChecks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthCheckProvider_HealthChecks_Call) Return(_a0 map[string]func(context.Context) error) *MockHealthCheckProvider_HealthChecks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthCheckProvider_HealthChecks_Call) RunAndReturn(run func() map[string]func(context.Context) error) *MockHealthCheckProvider_HealthChecks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthCheckProvider creates a new instance of MockHealthCheckProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthCheckProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthCheckProvider {
	mock := &MockHealthCheckProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
