// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHealthCheckRegisterer is an autogenerated mock type for the HealthCheckRegisterer type
type MockHealthCheckRegisterer struct {
	mock.Mock
}

type MockHealthCheckRegisterer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthCheckRegisterer) EXPECT() *MockHealthCheckRegisterer_Expecter {
	return &MockHealthCheckRegisterer_Expecter{mock: &_m.Mock}
}

// RegisterHealthCheck provides a mock function with given fields: name, check
func (_m *MockHealthCheckRegisterer) RegisterHealthCheck(name string, check func(context.Context) error) error {
	ret := _m.Called(name, check)

	if len(ret) == 0 {
		panic("no return value specified for RegisterHealthCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func(context.Context) error) error); ok {
		r0 = rf(name, check)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHealthCheckRegisterer_RegisterHealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterHealthCheck'
type MockHealthCheckRegisterer_RegisterHealthCheck_Call struct {
	*mock.Call
}

// RegisterHealthCheck is a helper method to define mock.On call
//   - name string
//   - check func(context.Context) error
func (_e *MockHealthCheckRegisterer_Expecter) RegisterHealthCheck(name interface{}, check interface{}) *MockHealthCheckRegisterer_RegisterHealthCheck_Call {
	return &MockHealthCheckRegisterer_RegisterHealthCheck_Call{Call: _e.mock.On("RegisterHealthCheck", name, check)}
}

func (_c *MockHealthCheckRegisterer_RegisterHealthCheck_Call) Run(run func(name string, check func(context.Context) error)) *MockHealthCheckRegisterer_RegisterHealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockHealthCheckRegisterer_RegisterHealthCheck_Call) Return(err error) *MockHealthCheckRegisterer_RegisterHealthCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHealthCheckRegisterer_RegisterHealthCheck_Call) RunAndReturn(run func(string, func(context.Context) error) error) *MockHealthCheckRegisterer_RegisterHealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthCheckRegisterer creates a new instance of MockHealthCheckRegisterer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthCheckRegisterer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthCheckRegisterer {
	mock := &MockHealthCheckRegisterer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
