// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	slog "log/slog"
)

// MockLoggerProvider is an autogenerated mock type for the LoggerProvider type
type MockLoggerProvider struct {
	mock.Mock
}

type MockLoggerProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoggerProvider) EXPECT() *MockLoggerProvider_Expecter {
	return &MockLoggerProvider_Expecter{mock: &_m.Mock}
}

// Logger provides a mock function with no fields
func (_m *MockLoggerProvider) Logger() *slog.Logger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *slog.Logger
	if rf, ok := ret.Get(0).(func() *slog.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slog.Logger)
		}
	}

	return r0
}

// MockLoggerProvider_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockLoggerProvider_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockLoggerProvider_Expecter) Logger() *MockLoggerProvider_Logger_Call {
	return &MockLoggerProvider_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockLoggerProvider_Logger_Call) Run(run func()) *MockLoggerProvider_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggerProvider_Logger_Call) Return(logger *slog.Logger) *MockLoggerProvider_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockLoggerProvider_Logger_Call) RunAndReturn(run func() *slog.Logger) *MockLoggerProvider_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoggerProvider creates a new instance of MockLoggerProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoggerProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoggerProvider {
	mock := &MockLoggerProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
