// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	modulex "github.com/mediusfy/modulex"
	mock "github.com/stretchr/testify/mock"
)

// MockModule is an autogenerated mock type for the Module type
type MockModule struct {
	mock.Mock
}

// DependsOn provides a mock function with no fields
func (_m *MockModule) DependsOn() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DependsOn")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// Init provides a mock function with given fields: ctx, reg
func (_m *MockModule) Init(ctx context.Context, reg modulex.Registry) error {
	ret := _m.Called(ctx, reg)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, modulex.Registry) error); ok {
		r0 = rf(ctx, reg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Name provides a mock function with no fields
func (_m *MockModule) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Start provides a mock function with given fields: ctx
func (_m *MockModule) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields: ctx
func (_m *MockModule) Stop(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockModule creates a new instance of MockModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModule {
	mock := &MockModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
