// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	modulex "github.com/mediusfy/modulex"
	mock "github.com/stretchr/testify/mock"
)

// MockModule is an autogenerated mock type for the Module type
type MockModule struct {
	mock.Mock
}

type MockModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModule) EXPECT() *MockModule_Expecter {
	return &MockModule_Expecter{mock: &_m.Mock}
}

// DependsOn provides a mock function with no fields
func (_m *MockModule) DependsOn() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DependsOn")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockModule_DependsOn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DependsOn'
type MockModule_DependsOn_Call struct {
	*mock.Call
}

// DependsOn is a helper method to define mock.On call
func (_e *MockModule_Expecter) DependsOn() *MockModule_DependsOn_Call {
	return &MockModule_DependsOn_Call{Call: _e.mock.On("DependsOn")}
}

func (_c *MockModule_DependsOn_Call) Run(run func()) *MockModule_DependsOn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockModule_DependsOn_Call) Return(_a0 []string) *MockModule_DependsOn_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockModule_DependsOn_Call) RunAndReturn(run func() []string) *MockModule_DependsOn_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function with given fields: ctx, reg
func (_m *MockModule) Init(ctx context.Context, reg modulex.Registry) error {
	ret := _m.Called(ctx, reg)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, modulex.Registry) error); ok {
		r0 = rf(ctx, reg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockModule_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockModule_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - reg modulex.Registry
func (_e *MockModule_Expecter) Init(ctx interface{}, reg interface{}) *MockModule_Init_Call {
	return &MockModule_Init_Call{Call: _e.mock.On("Init", ctx, reg)}
}

func (_c *MockModule_Init_Call) Run(run func(ctx context.Context, reg modulex.Registry)) *MockModule_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(modulex.Registry))
	})
	return _c
}

func (_c *MockModule_Init_Call) Return(_a0 error) *MockModule_Init_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockModule_Init_Call) RunAndReturn(run func(context.Context, modulex.Registry) error) *MockModule_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockModule) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockModule_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockModule_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockModule_Expecter) Name() *MockModule_Name_Call {
	return &MockModule_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockModule_Name_Call) Run(run func()) *MockModule_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockModule_Name_Call) Return(_a0 string) *MockModule_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockModule_Name_Call) RunAndReturn(run func() string) *MockModule_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockModule creates a new instance of MockModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModule {
	mock := &MockModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
