// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockReadinessProvider is an autogenerated mock type for the ReadinessProvider type
type MockReadinessProvider struct {
	mock.Mock
}

type MockReadinessProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadinessProvider) EXPECT() *MockReadinessProvider_Expecter {
	return &MockReadinessProvider_Expecter{mock: &_m.Mock}
}

// ReadinessChecks provides a mock function with no fields
func (_m *MockReadinessProvider) ReadinessChecks() map[string]func(context.Context) error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadinessChecks")
	}

	var r0 map[string]func(context.Context) error
	if rf, ok := ret.Get(0).(func() map[string]func(context.Context) error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]func(context.Context) error)
		}
	}

	return r0
}

// MockReadinessProvider_ReadinessChecks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadinessChecks'
type MockReadinessProvider_ReadinessChecks_Call struct {
	*mock.Call
}

// ReadinessChecks is a helper method to define mock.On call
func (_e *MockReadinessProvider_Expecter) ReadinessChecks() *MockReadinessProvider_ReadinessChecks_Call {
	return &MockReadinessProvider_ReadinessChecks_Call{Call: _e.mock.On("ReadinessChecks")}
}

func (_c *MockReadinessProvider_ReadinessChecks_Call) Run(run func()) *MockReadinessProvider_ReadinessChecks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReadinessProvider_ReadinessChecks_Call) Return(checks map[string]func(context.Context) error) *MockReadinessProvider_ReadinessChecks_Call {
	_c.Call.Return(checks)
	return _c
}

func (_c *MockReadinessProvider_ReadinessChecks_Call) RunAndReturn(run func() map[string]func(context.Context) error) *MockReadinessProvider_ReadinessChecks_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReadinessProvider creates a new instance of MockReadinessProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadinessProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadinessProvider {
	mock := &MockReadinessProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
