// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockReadinessRegistrar is an autogenerated mock type for the ReadinessRegistrar type
type MockReadinessRegistrar struct {
	mock.Mock
}

type MockReadinessRegistrar_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadinessRegistrar) EXPECT() *MockReadinessRegistrar_Expecter {
	return &MockReadinessRegistrar_Expecter{mock: &_m.Mock}
}

// RegisterReadinessCheck provides a mock function with given fields: name, check
func (_m *MockReadinessRegistrar) RegisterReadinessCheck(name string, check func(context.Context) error) error {
	ret := _m.Called(name, check)

	if len(ret) == 0 {
		panic("no return value specified for RegisterReadinessCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func(context.Context) error) error); ok {
		r0 = rf(name, check)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReadinessRegistrar_RegisterReadinessCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterReadinessCheck'
type MockReadinessRegistrar_RegisterReadinessCheck_Call struct {
	*mock.Call
}

// RegisterReadinessCheck is a helper method to define mock.On call
//   - name string
//   - check func(context.Context) error
func (_e *MockReadinessRegistrar_Expecter) RegisterReadinessCheck(name interface{}, check interface{}) *MockReadinessRegistrar_RegisterReadinessCheck_Call {
	return &MockReadinessRegistrar_RegisterReadinessCheck_Call{Call: _e.mock.On("RegisterReadinessCheck", name, check)}
}

func (_c *MockReadinessRegistrar_RegisterReadinessCheck_Call) Run(run func(name string, check func(context.Context) error)) *MockReadinessRegistrar_RegisterReadinessCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockReadinessRegistrar_RegisterReadinessCheck_Call) Return(_a0 error) *MockReadinessRegistrar_RegisterReadinessCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReadinessRegistrar_RegisterReadinessCheck_Call) RunAndReturn(run func(string, func(context.Context) error) error) *MockReadinessRegistrar_RegisterReadinessCheck_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReadinessRegistrar creates a new instance of MockReadinessRegistrar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadinessRegistrar(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadinessRegistrar {
	mock := &MockReadinessRegistrar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
