// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockReadinessRegisterer is an autogenerated mock type for the ReadinessRegisterer type
type MockReadinessRegisterer struct {
	mock.Mock
}

type MockReadinessRegisterer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadinessRegisterer) EXPECT() *MockReadinessRegisterer_Expecter {
	return &MockReadinessRegisterer_Expecter{mock: &_m.Mock}
}

// RegisterReadinessCheck provides a mock function with given fields: name, check
func (_m *MockReadinessRegisterer) RegisterReadinessCheck(name string, check func(context.Context) error) error {
	ret := _m.Called(name, check)

	if len(ret) == 0 {
		panic("no return value specified for RegisterReadinessCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func(context.Context) error) error); ok {
		r0 = rf(name, check)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReadinessRegisterer_RegisterReadinessCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterReadinessCheck'
type MockReadinessRegisterer_RegisterReadinessCheck_Call struct {
	*mock.Call
}

// RegisterReadinessCheck is a helper method to define mock.On call
//   - name string
//   - check func(context.Context) error
func (_e *MockReadinessRegisterer_Expecter) RegisterReadinessCheck(name interface{}, check interface{}) *MockReadinessRegisterer_RegisterReadinessCheck_Call {
	return &MockReadinessRegisterer_RegisterReadinessCheck_Call{Call: _e.mock.On("RegisterReadinessCheck", name, check)}
}

func (_c *MockReadinessRegisterer_RegisterReadinessCheck_Call) Run(run func(name string, check func(context.Context) error)) *MockReadinessRegisterer_RegisterReadinessCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockReadinessRegisterer_RegisterReadinessCheck_Call) Return(err error) *MockReadinessRegisterer_RegisterReadinessCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReadinessRegisterer_RegisterReadinessCheck_Call) RunAndReturn(run func(string, func(context.Context) error) error) *MockReadinessRegisterer_RegisterReadinessCheck_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReadinessRegisterer creates a new instance of MockReadinessRegisterer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadinessRegisterer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadinessRegisterer {
	mock := &MockReadinessRegisterer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
