// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	modulex "github.com/mediusfy/modulex"
	mock "github.com/stretchr/testify/mock"

	slog "log/slog"
)

// MockRegistry is an autogenerated mock type for the Registry type
type MockRegistry struct {
	mock.Mock
}

type MockRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistry) EXPECT() *MockRegistry_Expecter {
	return &MockRegistry_Expecter{mock: &_m.Mock}
}

// EventBus provides a mock function with no fields
func (_m *MockRegistry) EventBus() modulex.EventBus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventBus")
	}

	var r0 modulex.EventBus
	if rf, ok := ret.Get(0).(func() modulex.EventBus); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(modulex.EventBus)
		}
	}

	return r0
}

// MockRegistry_EventBus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventBus'
type MockRegistry_EventBus_Call struct {
	*mock.Call
}

// EventBus is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) EventBus() *MockRegistry_EventBus_Call {
	return &MockRegistry_EventBus_Call{Call: _e.mock.On("EventBus")}
}

func (_c *MockRegistry_EventBus_Call) Run(run func()) *MockRegistry_EventBus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_EventBus_Call) Return(eb modulex.EventBus) *MockRegistry_EventBus_Call {
	_c.Call.Return(eb)
	return _c
}

func (_c *MockRegistry_EventBus_Call) RunAndReturn(run func() modulex.EventBus) *MockRegistry_EventBus_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function with given fields: target
func (_m *MockRegistry) GetConfig(target interface{}) error {
	ret := _m.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(target)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegistry_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockRegistry_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
//   - target interface{}
func (_e *MockRegistry_Expecter) GetConfig(target interface{}) *MockRegistry_GetConfig_Call {
	return &MockRegistry_GetConfig_Call{Call: _e.mock.On("GetConfig", target)}
}

func (_c *MockRegistry_GetConfig_Call) Run(run func(target interface{})) *MockRegistry_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockRegistry_GetConfig_Call) Return(err error) *MockRegistry_GetConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistry_GetConfig_Call) RunAndReturn(run func(interface{}) error) *MockRegistry_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// Go provides a mock function with given fields: ctx, taskName, fn
func (_m *MockRegistry) Go(ctx context.Context, taskName string, fn func(context.Context) error) (*modulex.TaskHandle, error) {
	ret := _m.Called(ctx, taskName, fn)

	if len(ret) == 0 {
		panic("no return value specified for Go")
	}

	var r0 *modulex.TaskHandle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func(context.Context) error) (*modulex.TaskHandle, error)); ok {
		return rf(ctx, taskName, fn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, func(context.Context) error) *modulex.TaskHandle); ok {
		r0 = rf(ctx, taskName, fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modulex.TaskHandle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, func(context.Context) error) error); ok {
		r1 = rf(ctx, taskName, fn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegistry_Go_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Go'
type MockRegistry_Go_Call struct {
	*mock.Call
}

// Go is a helper method to define mock.On call
//   - ctx context.Context
//   - taskName string
//   - fn func(context.Context) error
func (_e *MockRegistry_Expecter) Go(ctx interface{}, taskName interface{}, fn interface{}) *MockRegistry_Go_Call {
	return &MockRegistry_Go_Call{Call: _e.mock.On("Go", ctx, taskName, fn)}
}

func (_c *MockRegistry_Go_Call) Run(run func(ctx context.Context, taskName string, fn func(context.Context) error)) *MockRegistry_Go_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(func(context.Context) error))
	})
	return _c
}

func (_c *MockRegistry_Go_Call) Return(handle *modulex.TaskHandle, err error) *MockRegistry_Go_Call {
	_c.Call.Return(handle, err)
	return _c
}

func (_c *MockRegistry_Go_Call) RunAndReturn(run func(context.Context, string, func(context.Context) error) (*modulex.TaskHandle, error)) *MockRegistry_Go_Call {
	_c.Call.Return(run)
	return _c
}

// HealthChecks provides a mock function with no fields
func (_m *MockRegistry) HealthChecks() map[string]func(context.Context) error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthChecks")
	}

	var r0 map[string]func(context.Context) error
	if rf, ok := ret.Get(0).(func() map[string]func(context.Context) error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]func(context.Context) error)
		}
	}

	return r0
}

// MockRegistry_HealthChecks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthChecks'
type MockRegistry_HealthChecks_Call struct {
	*mock.Call
}

// HealthChecks is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) HealthChecks() *MockRegistry_HealthChecks_Call {
	return &MockRegistry_HealthChecks_Call{Call: _e.mock.On("HealthChecks")}
}

func (_c *MockRegistry_HealthChecks_Call) Run(run func()) *MockRegistry_HealthChecks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_HealthChecks_Call) Return(checks map[string]func(context.Context) error) *MockRegistry_HealthChecks_Call {
	_c.Call.Return(checks)
	return _c
}

func (_c *MockRegistry_HealthChecks_Call) RunAndReturn(run func() map[string]func(context.Context) error) *MockRegistry_HealthChecks_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function with no fields
func (_m *MockRegistry) Logger() *slog.Logger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *slog.Logger
	if rf, ok := ret.Get(0).(func() *slog.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slog.Logger)
		}
	}

	return r0
}

// MockRegistry_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockRegistry_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) Logger() *MockRegistry_Logger_Call {
	return &MockRegistry_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockRegistry_Logger_Call) Run(run func()) *MockRegistry_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_Logger_Call) Return(logger *slog.Logger) *MockRegistry_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockRegistry_Logger_Call) RunAndReturn(run func() *slog.Logger) *MockRegistry_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// ReadinessChecks provides a mock function with no fields
func (_m *MockRegistry) ReadinessChecks() map[string]func(context.Context) error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadinessChecks")
	}

	var r0 map[string]func(context.Context) error
	if rf, ok := ret.Get(0).(func() map[string]func(context.Context) error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]func(context.Context) error)
		}
	}

	return r0
}

// MockRegistry_ReadinessChecks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadinessChecks'
type MockRegistry_ReadinessChecks_Call struct {
	*mock.Call
}

// ReadinessChecks is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) ReadinessChecks() *MockRegistry_ReadinessChecks_Call {
	return &MockRegistry_ReadinessChecks_Call{Call: _e.mock.On("ReadinessChecks")}
}

func (_c *MockRegistry_ReadinessChecks_Call) Run(run func()) *MockRegistry_ReadinessChecks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_ReadinessChecks_Call) Return(checks map[string]func(context.Context) error) *MockRegistry_ReadinessChecks_Call {
	_c.Call.Return(checks)
	return _c
}

func (_c *MockRegistry_ReadinessChecks_Call) RunAndReturn(run func() map[string]func(context.Context) error) *MockRegistry_ReadinessChecks_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterHealthCheck provides a mock function with given fields: name, check
func (_m *MockRegistry) RegisterHealthCheck(name string, check func(context.Context) error) error {
	ret := _m.Called(name, check)

	if len(ret) == 0 {
		panic("no return value specified for RegisterHealthCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func(context.Context) error) error); ok {
		r0 = rf(name, check)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegistry_RegisterHealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterHealthCheck'
type MockRegistry_RegisterHealthCheck_Call struct {
	*mock.Call
}

// RegisterHealthCheck is a helper method to define mock.On call
//   - name string
//   - check func(context.Context) error
func (_e *MockRegistry_Expecter) RegisterHealthCheck(name interface{}, check interface{}) *MockRegistry_RegisterHealthCheck_Call {
	return &MockRegistry_RegisterHealthCheck_Call{Call: _e.mock.On("RegisterHealthCheck", name, check)}
}

func (_c *MockRegistry_RegisterHealthCheck_Call) Run(run func(name string, check func(context.Context) error)) *MockRegistry_RegisterHealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockRegistry_RegisterHealthCheck_Call) Return(err error) *MockRegistry_RegisterHealthCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistry_RegisterHealthCheck_Call) RunAndReturn(run func(string, func(context.Context) error) error) *MockRegistry_RegisterHealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterReadinessCheck provides a mock function with given fields: name, check
func (_m *MockRegistry) RegisterReadinessCheck(name string, check func(context.Context) error) error {
	ret := _m.Called(name, check)

	if len(ret) == 0 {
		panic("no return value specified for RegisterReadinessCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func(context.Context) error) error); ok {
		r0 = rf(name, check)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegistry_RegisterReadinessCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterReadinessCheck'
type MockRegistry_RegisterReadinessCheck_Call struct {
	*mock.Call
}

// RegisterReadinessCheck is a helper method to define mock.On call
//   - name string
//   - check func(context.Context) error
func (_e *MockRegistry_Expecter) RegisterReadinessCheck(name interface{}, check interface{}) *MockRegistry_RegisterReadinessCheck_Call {
	return &MockRegistry_RegisterReadinessCheck_Call{Call: _e.mock.On("RegisterReadinessCheck", name, check)}
}

func (_c *MockRegistry_RegisterReadinessCheck_Call) Run(run func(name string, check func(context.Context) error)) *MockRegistry_RegisterReadinessCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockRegistry_RegisterReadinessCheck_Call) Return(err error) *MockRegistry_RegisterReadinessCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistry_RegisterReadinessCheck_Call) RunAndReturn(run func(string, func(context.Context) error) error) *MockRegistry_RegisterReadinessCheck_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterService provides a mock function with given fields: name, svc
func (_m *MockRegistry) RegisterService(name string, svc interface{}) error {
	ret := _m.Called(name, svc)

	if len(ret) == 0 {
		panic("no return value specified for RegisterService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(name, svc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegistry_RegisterService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterService'
type MockRegistry_RegisterService_Call struct {
	*mock.Call
}

// RegisterService is a helper method to define mock.On call
//   - name string
//   - svc interface{}
func (_e *MockRegistry_Expecter) RegisterService(name interface{}, svc interface{}) *MockRegistry_RegisterService_Call {
	return &MockRegistry_RegisterService_Call{Call: _e.mock.On("RegisterService", name, svc)}
}

func (_c *MockRegistry_RegisterService_Call) Run(run func(name string, svc interface{})) *MockRegistry_RegisterService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *MockRegistry_RegisterService_Call) Return(err error) *MockRegistry_RegisterService_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistry_RegisterService_Call) RunAndReturn(run func(string, interface{}) error) *MockRegistry_RegisterService_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveService provides a mock function with given fields: name
func (_m *MockRegistry) ResolveService(name string) (interface{}, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ResolveService")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interface{}, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegistry_ResolveService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveService'
type MockRegistry_ResolveService_Call struct {
	*mock.Call
}

// ResolveService is a helper method to define mock.On call
//   - name string
func (_e *MockRegistry_Expecter) ResolveService(name interface{}) *MockRegistry_ResolveService_Call {
	return &MockRegistry_ResolveService_Call{Call: _e.mock.On("ResolveService", name)}
}

func (_c *MockRegistry_ResolveService_Call) Run(run func(name string)) *MockRegistry_ResolveService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistry_ResolveService_Call) Return(svc interface{}, err error) *MockRegistry_ResolveService_Call {
	_c.Call.Return(svc, err)
	return _c
}

func (_c *MockRegistry_ResolveService_Call) RunAndReturn(run func(string) (interface{}, error)) *MockRegistry_ResolveService_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
