// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	chi "github.com/go-chi/chi/v5"

	mock "github.com/stretchr/testify/mock"

	modulex "github.com/mediusfy/modulex"

	slog "log/slog"

	trace "go.opentelemetry.io/otel/trace"
)

// MockRegistry is an autogenerated mock type for the Registry type
type MockRegistry struct {
	mock.Mock
}

// EventBus provides a mock function with no fields
func (_m *MockRegistry) EventBus() modulex.EventBus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventBus")
	}

	var r0 modulex.EventBus
	if rf, ok := ret.Get(0).(func() modulex.EventBus); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(modulex.EventBus)
		}
	}

	return r0
}

// GetConfig provides a mock function with given fields: target
func (_m *MockRegistry) GetConfig(target interface{}) error {
	ret := _m.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(target)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Go provides a mock function with given fields: ctx, taskName, fn
func (_m *MockRegistry) Go(ctx context.Context, taskName string, fn func(context.Context)) {
	_m.Called(ctx, taskName, fn)
}

// Logger provides a mock function with no fields
func (_m *MockRegistry) Logger() *slog.Logger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *slog.Logger
	if rf, ok := ret.Get(0).(func() *slog.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slog.Logger)
		}
	}

	return r0
}

// RegisterService provides a mock function with given fields: name, svc
func (_m *MockRegistry) RegisterService(name string, svc interface{}) error {
	ret := _m.Called(name, svc)

	if len(ret) == 0 {
		panic("no return value specified for RegisterService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(name, svc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResolveService provides a mock function with given fields: name
func (_m *MockRegistry) ResolveService(name string) (interface{}, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ResolveService")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interface{}, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Router provides a mock function with no fields
func (_m *MockRegistry) Router() chi.Router {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Router")
	}

	var r0 chi.Router
	if rf, ok := ret.Get(0).(func() chi.Router); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chi.Router)
		}
	}

	return r0
}

// Tracer provides a mock function with no fields
func (_m *MockRegistry) Tracer() trace.Tracer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tracer")
	}

	var r0 trace.Tracer
	if rf, ok := ret.Get(0).(func() trace.Tracer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(trace.Tracer)
		}
	}

	return r0
}

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
