// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockServiceRegisterer is an autogenerated mock type for the ServiceRegisterer type
type MockServiceRegisterer struct {
	mock.Mock
}

type MockServiceRegisterer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceRegisterer) EXPECT() *MockServiceRegisterer_Expecter {
	return &MockServiceRegisterer_Expecter{mock: &_m.Mock}
}

// RegisterService provides a mock function with given fields: name, svc
func (_m *MockServiceRegisterer) RegisterService(name string, svc interface{}) error {
	ret := _m.Called(name, svc)

	if len(ret) == 0 {
		panic("no return value specified for RegisterService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(name, svc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceRegisterer_RegisterService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterService'
type MockServiceRegisterer_RegisterService_Call struct {
	*mock.Call
}

// RegisterService is a helper method to define mock.On call
//   - name string
//   - svc interface{}
func (_e *MockServiceRegisterer_Expecter) RegisterService(name interface{}, svc interface{}) *MockServiceRegisterer_RegisterService_Call {
	return &MockServiceRegisterer_RegisterService_Call{Call: _e.mock.On("RegisterService", name, svc)}
}

func (_c *MockServiceRegisterer_RegisterService_Call) Run(run func(name string, svc interface{})) *MockServiceRegisterer_RegisterService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *MockServiceRegisterer_RegisterService_Call) Return(err error) *MockServiceRegisterer_RegisterService_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceRegisterer_RegisterService_Call) RunAndReturn(run func(string, interface{}) error) *MockServiceRegisterer_RegisterService_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceRegisterer creates a new instance of MockServiceRegisterer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceRegisterer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceRegisterer {
	mock := &MockServiceRegisterer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
