// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockServiceResolver is an autogenerated mock type for the ServiceResolver type
type MockServiceResolver struct {
	mock.Mock
}

type MockServiceResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceResolver) EXPECT() *MockServiceResolver_Expecter {
	return &MockServiceResolver_Expecter{mock: &_m.Mock}
}

// ResolveService provides a mock function with given fields: name
func (_m *MockServiceResolver) ResolveService(name string) (interface{}, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ResolveService")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interface{}, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceResolver_ResolveService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveService'
type MockServiceResolver_ResolveService_Call struct {
	*mock.Call
}

// ResolveService is a helper method to define mock.On call
//   - name string
func (_e *MockServiceResolver_Expecter) ResolveService(name interface{}) *MockServiceResolver_ResolveService_Call {
	return &MockServiceResolver_ResolveService_Call{Call: _e.mock.On("ResolveService", name)}
}

func (_c *MockServiceResolver_ResolveService_Call) Run(run func(name string)) *MockServiceResolver_ResolveService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockServiceResolver_ResolveService_Call) Return(svc interface{}, err error) *MockServiceResolver_ResolveService_Call {
	_c.Call.Return(svc, err)
	return _c
}

func (_c *MockServiceResolver_ResolveService_Call) RunAndReturn(run func(string) (interface{}, error)) *MockServiceResolver_ResolveService_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceResolver creates a new instance of MockServiceResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceResolver {
	mock := &MockServiceResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
