// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockServiceRegistry is an autogenerated mock type for the ServiceRegistry type
type MockServiceRegistry struct {
	mock.Mock
}

type MockServiceRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceRegistry) EXPECT() *MockServiceRegistry_Expecter {
	return &MockServiceRegistry_Expecter{mock: &_m.Mock}
}

// RegisterService provides a mock function with given fields: name, svc
func (_m *MockServiceRegistry) RegisterService(name string, svc interface{}) error {
	ret := _m.Called(name, svc)

	if len(ret) == 0 {
		panic("no return value specified for RegisterService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(name, svc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceRegistry_RegisterService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterService'
type MockServiceRegistry_RegisterService_Call struct {
	*mock.Call
}

// RegisterService is a helper method to define mock.On call
//   - name string
//   - svc interface{}
func (_e *MockServiceRegistry_Expecter) RegisterService(name interface{}, svc interface{}) *MockServiceRegistry_RegisterService_Call {
	return &MockServiceRegistry_RegisterService_Call{Call: _e.mock.On("RegisterService", name, svc)}
}

func (_c *MockServiceRegistry_RegisterService_Call) Run(run func(name string, svc interface{})) *MockServiceRegistry_RegisterService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *MockServiceRegistry_RegisterService_Call) Return(err error) *MockServiceRegistry_RegisterService_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceRegistry_RegisterService_Call) RunAndReturn(run func(string, interface{}) error) *MockServiceRegistry_RegisterService_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveService provides a mock function with given fields: name
func (_m *MockServiceRegistry) ResolveService(name string) (interface{}, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ResolveService")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interface{}, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServiceRegistry_ResolveService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveService'
type MockServiceRegistry_ResolveService_Call struct {
	*mock.Call
}

// ResolveService is a helper method to define mock.On call
//   - name string
func (_e *MockServiceRegistry_Expecter) ResolveService(name interface{}) *MockServiceRegistry_ResolveService_Call {
	return &MockServiceRegistry_ResolveService_Call{Call: _e.mock.On("ResolveService", name)}
}

func (_c *MockServiceRegistry_ResolveService_Call) Run(run func(name string)) *MockServiceRegistry_ResolveService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockServiceRegistry_ResolveService_Call) Return(svc interface{}, err error) *MockServiceRegistry_ResolveService_Call {
	_c.Call.Return(svc, err)
	return _c
}

func (_c *MockServiceRegistry_ResolveService_Call) RunAndReturn(run func(string) (interface{}, error)) *MockServiceRegistry_ResolveService_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceRegistry creates a new instance of MockServiceRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceRegistry {
	mock := &MockServiceRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
