// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStarter is an autogenerated mock type for the Starter type
type MockStarter struct {
	mock.Mock
}

type MockStarter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStarter) EXPECT() *MockStarter_Expecter {
	return &MockStarter_Expecter{mock: &_m.Mock}
}

// Start provides a mock function with given fields: ctx
func (_m *MockStarter) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStarter_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockStarter_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStarter_Expecter) Start(ctx interface{}) *MockStarter_Start_Call {
	return &MockStarter_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockStarter_Start_Call) Run(run func(ctx context.Context)) *MockStarter_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStarter_Start_Call) Return(err error) *MockStarter_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStarter_Start_Call) RunAndReturn(run func(context.Context) error) *MockStarter_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStarter creates a new instance of MockStarter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStarter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStarter {
	mock := &MockStarter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
