// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStopper is an autogenerated mock type for the Stopper type
type MockStopper struct {
	mock.Mock
}

type MockStopper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStopper) EXPECT() *MockStopper_Expecter {
	return &MockStopper_Expecter{mock: &_m.Mock}
}

// Stop provides a mock function with given fields: ctx
func (_m *MockStopper) Stop(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStopper_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockStopper_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStopper_Expecter) Stop(ctx interface{}) *MockStopper_Stop_Call {
	return &MockStopper_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *MockStopper_Stop_Call) Run(run func(ctx context.Context)) *MockStopper_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStopper_Stop_Call) Return(err error) *MockStopper_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStopper_Stop_Call) RunAndReturn(run func(context.Context) error) *MockStopper_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStopper creates a new instance of MockStopper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStopper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStopper {
	mock := &MockStopper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
