// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	modulex "github.com/mediusfy/modulex"
	mock "github.com/stretchr/testify/mock"
)

// MockTaskSpawner is an autogenerated mock type for the TaskSpawner type
type MockTaskSpawner struct {
	mock.Mock
}

type MockTaskSpawner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskSpawner) EXPECT() *MockTaskSpawner_Expecter {
	return &MockTaskSpawner_Expecter{mock: &_m.Mock}
}

// Go provides a mock function with given fields: ctx, taskName, fn
func (_m *MockTaskSpawner) Go(ctx context.Context, taskName string, fn func(context.Context) error) (*modulex.TaskHandle, error) {
	ret := _m.Called(ctx, taskName, fn)

	if len(ret) == 0 {
		panic("no return value specified for Go")
	}

	var r0 *modulex.TaskHandle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func(context.Context) error) (*modulex.TaskHandle, error)); ok {
		return rf(ctx, taskName, fn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, func(context.Context) error) *modulex.TaskHandle); ok {
		r0 = rf(ctx, taskName, fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modulex.TaskHandle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, func(context.Context) error) error); ok {
		r1 = rf(ctx, taskName, fn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskSpawner_Go_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Go'
type MockTaskSpawner_Go_Call struct {
	*mock.Call
}

// Go is a helper method to define mock.On call
//   - ctx context.Context
//   - taskName string
//   - fn func(context.Context) error
func (_e *MockTaskSpawner_Expecter) Go(ctx interface{}, taskName interface{}, fn interface{}) *MockTaskSpawner_Go_Call {
	return &MockTaskSpawner_Go_Call{Call: _e.mock.On("Go", ctx, taskName, fn)}
}

func (_c *MockTaskSpawner_Go_Call) Run(run func(ctx context.Context, taskName string, fn func(context.Context) error)) *MockTaskSpawner_Go_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(func(context.Context) error))
	})
	return _c
}

func (_c *MockTaskSpawner_Go_Call) Return(handle *modulex.TaskHandle, err error) *MockTaskSpawner_Go_Call {
	_c.Call.Return(handle, err)
	return _c
}

func (_c *MockTaskSpawner_Go_Call) RunAndReturn(run func(context.Context, string, func(context.Context) error) (*modulex.TaskHandle, error)) *MockTaskSpawner_Go_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskSpawner creates a new instance of MockTaskSpawner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskSpawner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskSpawner {
	mock := &MockTaskSpawner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
