// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: examples/deployment/notification/notificationpb/notification.proto

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SendRequest carries the notification message, matching
// ports.Sender.Send's message parameter.
type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_examples_deployment_notification_notificationpb_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_deployment_notification_notificationpb_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_examples_deployment_notification_notificationpb_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SendResponse is intentionally empty: ports.Sender.Send returns only an
// error, so success carries no payload beyond an OK gRPC status.
type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_examples_deployment_notification_notificationpb_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_deployment_notification_notificationpb_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_examples_deployment_notification_notificationpb_notification_proto_rawDescGZIP(), []int{1}
}

var File_examples_deployment_notification_notificationpb_notification_proto protoreflect.FileDescriptor

const file_examples_deployment_notification_notificationpb_notification_proto_rawDesc = "" +
	"\n" +
	"Bexamples/deployment/notification/notificationpb/notification.proto\x12\x0enotificationpb\"'\n" +
	"\vSendRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x0e\n" +
	"\fSendResponse2Q\n" +
	"\fNotification\x12A\n" +
	"\x04Send\x12\x1b.notificationpb.SendRequest\x1a\x1c.notificationpb.SendResponseBMZKgithub.com/mediusfy/modulex/examples/deployment/notification/notificationpbb\x06proto3"

var (
	file_examples_deployment_notification_notificationpb_notification_proto_rawDescOnce sync.Once
	file_examples_deployment_notification_notificationpb_notification_proto_rawDescData []byte
)

func file_examples_deployment_notification_notificationpb_notification_proto_rawDescGZIP() []byte {
	file_examples_deployment_notification_notificationpb_notification_proto_rawDescOnce.Do(func() {
		file_examples_deployment_notification_notificationpb_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_deployment_notification_notificationpb_notification_proto_rawDesc), len(file_examples_deployment_notification_notificationpb_notification_proto_rawDesc)))
	})
	return file_examples_deployment_notification_notificationpb_notification_proto_rawDescData
}

var file_examples_deployment_notification_notificationpb_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_deployment_notification_notificationpb_notification_proto_goTypes = []any{
	(*SendRequest)(nil),  // 0: notificationpb.SendRequest
	(*SendResponse)(nil), // 1: notificationpb.SendResponse
}
var file_examples_deployment_notification_notificationpb_notification_proto_depIdxs = []int32{
	0, // 0: notificationpb.Notification.Send:input_type -> notificationpb.SendRequest
	1, // 1: notificationpb.Notification.Send:output_type -> notificationpb.SendResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_deployment_notification_notificationpb_notification_proto_init() }
func file_examples_deployment_notification_notificationpb_notification_proto_init() {
	if File_examples_deployment_notification_notificationpb_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_deployment_notification_notificationpb_notification_proto_rawDesc), len(file_examples_deployment_notification_notificationpb_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_deployment_notification_notificationpb_notification_proto_goTypes,
		DependencyIndexes: file_examples_deployment_notification_notificationpb_notification_proto_depIdxs,
		MessageInfos:      file_examples_deployment_notification_notificationpb_notification_proto_msgTypes,
	}.Build()
	File_examples_deployment_notification_notificationpb_notification_proto = out.File
	file_examples_deployment_notification_notificationpb_notification_proto_goTypes = nil
	file_examples_deployment_notification_notificationpb_notification_proto_depIdxs = nil
}
